### ISSUE TITLE
Git clone url is wrong

### ISSUE THREAD

**Issue by KristianRykkje** [HelgeSverre/ollama-gui#1]
In readme: 

`git clone git@github.com:HelgeSverre/ollama-gui.git`
gir: `fatal: Could not read from remote repository.`

Riktig url: `https://github.com/HelgeSverre/ollama-gui.git`

**Comment by KristianRykkje** [comment]
Fikk ikke lov å lage pull request...

**Comment by HelgeSverre** [comment]
Have you added your SSH key in Github?
