### ISSUE TITLE
Changing the API URL has no effect

### ISSUE THREAD

**Issue by tmfksoft** [HelgeSverre/ollama-gui#11]
When changing the API URL the settings are updated in localStorage but don't affect the chat client.

The API_BASE_URL appears to be hardcoded in src/services/api.ts

Jerry rigging it to
`const API_BASE_URL = baseUrl.value || 'http://localhost:11434/api';`

Allows it to work but I'm not familiar enough with Vue to know if this is the right way to do it.
If it is, I'm willing to PR it.

**Comment by HelgeSverre** [comment]
Will look into this soon.

**Comment by HelgeSverre** [comment]
✅ Should be fixed now.

Pull down the latest version (`git checkout main && git pull && yarn && yarn dev` in the ollama-gui folder), or use the [web version](https://ollama-gui.vercel.app) by whitelisting the origin when starting `ollama serve`:

```shell
OLLAMA_ORIGINS=https://ollama-gui.vercel.app ollama serve
```
