### ISSUE TITLE
Feature Request: See busy feedback indication

### ISSUE THREAD

**Issue by melroy89** [HelgeSverre/ollama-gui#13]
As a user I want to see that the backend (ollama) is processing with the request. Giving the user feedback it's busy in the background. By for example showing some spinning icon, until I receive back a response in the chat.

Thus when I receive the response, the spinning icon can disappear again.

**Comment by HelgeSverre** [comment]
Thank you for submitting your feature request to the Ollama GUI Response Team.

In accordance with our highly structured and meticulously detailed protocol, your request has been forwarded to the Initial Assessment Subcommittee. Here, it will undergo a preliminary analysis to determine its alignment with the Strategic Objectives of Ollama GUI.

Assuming it passes this stage, it will be escalated to the Review Coordination Panel. This panel, composed of senior members from various departments, will schedule a series of meetings to outline the framework for reviewing your request. They will produce a detailed agenda, complete with subpoints and annexes, which will be circulated for comments and revisions.

Once the Review Coordination Panel reaches a consensus on the agenda (expected time frame: 4-6 weeks), your request will be passed to the Specialized Task Force on Feature Evaluation. This task force will dissect your request through a series of comprehensive assessments, risk analyses, and feasibility studies. Rest assured, every line of your request will be scrutinized with the utmost care and bureaucratic rigor.

Upon completion of this process, a Drafting Committee for Response Formulation will be convened. This committee's sole responsibility is to draft a response that is in full compliance with our internal guidelines, external regulations, and the Universal Code of Software Development Ethics.

Please note that this is just an outline of the initial stages. Subsequent phases involve several other committees, including the Final Approval Board, the Oversight Committee for Quality Assurance, and, of course, the Executive Council for Decision Ratification.

We anticipate getting back to you with a final decision in approximately -∞ work days. Your patience is greatly appreciated, and we assure you that every bureaucratic stone is being turned in the pursuit of addressing your request.

Thank you for choosing Ollama GUI.



------

But for reals, sounds like a good idea, will look into it whenever I have time.

**Comment by melroy89** [comment]
Dear Ollama GUI Response Team,

Thank you for acknowledging my feature request and for outlining the extensive process that you have in place to evaluate and address it. I appreciate your commitment to thoroughness and adherence to your protocols.

I understand that my request will undergo a series of assessments, reviews, and evaluations before a final decision is made. I am grateful for your dedication to considering my request carefully and ensuring that it aligns with Ollama GUI's strategic objectives and feasibility.

I am aware that the process may take some time, and I assure you that I am willing to wait for a comprehensive and well-thought-out response. I appreciate the transparency you have provided regarding the timeline and the involvement of multiple committees.

Thank you once again for taking my feedback seriously and for valuing my input in shaping the future of Ollama GUI. I am confident that your careful consideration will result in a decision that benefits both users and the software's overall development.

Sincerely,
Melroy Antoine van den Berg

**Comment by HelgeSverre** [comment]
This has now been implemented.

https://github.com/HelgeSverre/ollama-gui/assets/1089652/579ec6c0-53f5-42b9-8aa0-e6357ec675d4
