### ISSUE TITLE
Using Ollama chat API

### ISSUE THREAD

**Issue by emsi** [HelgeSverre/ollama-gui#16]
Hi!

There's a relatively new ollama chat API:
https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-chat-completion

It works in a very similar way to openAi chat api:

```
curl http://localhost:11434/api/chat -d '{
  "model": "llama2",
  "messages": [
    {
      "role": "user",
      "content": "why is the sky blue?"
    }
  ]
}'
```

Since I've experienced a lot of problems with ollama-gui and newer models (e.g. nous-hermes2-mixtral) that look like prompt formatting issues I think that migrating to this API would solve most of them.

![image](https://github.com/HelgeSverre/ollama-gui/assets/433383/a84da3e0-b65f-4ca4-9645-f354d963c529)

**Comment by HelgeSverre** [comment]
Seems like a good idea, will investigate over the weekend

**Comment by emsi** [comment]
> Seems like a good idea, will investigate over the weekend

Any thoughts on that?

**Comment by HelgeSverre** [comment]
💰 **Bug bounty** of __$ 30__ to whomever implements this.*


> (*) Paid via PayPal or whatever payment service where you can send me a link, no wire transfers.

**Comment by emsi** [comment]
> 💰 **Bug bounty** of **$30** to whomever implements this.*
> 
> > (*) Paid via PayPal or whatever payment service where you can send me a link, no wire transfers.

Ollama has implemented OpenAI compatible api interface so you can point to that:

https://ollama.ai/blog/openai-compatibility

**Comment by ebanDev** [comment]
Hi! If this still something you'd like to work on, I'd be eager to have to issue assigned :)

**Comment by HelgeSverre** [comment]
Did someone do this, i feel like someone did this, but I'm not certain...

**Comment by SwingBling** [comment]
I just started using Ollama GUI today, and I also see similar prompt issues when using the model deepseek-coder-v2. Example image here:
![image](https://github.com/user-attachments/assets/54756d1e-af8d-401b-93a2-94fb7b4bd94a)

**Comment by HelgeSverre** [comment]
Should be fixed.
