### ISSUE TITLE
Alternative installation method

### ISSUE THREAD

**Issue by evrenesat** [HelgeSverre/ollama-gui#28]
Hi, thanks for the ollama-gui. I wish at some point it will be included with the base ollama setup. For people who already have Python (or another webserver) on their local, I want to share an alternative installation method that doesn't require node or using remote hosted version with OLLAMA_ORIGINS env. var.

```bash
wget -m https://ollama-gui.vercel.app
cd ollama-gui.vercel.app
open http://localhost:8000; python -m http.server
```
Once we open the ollama-gui, python server can be shutdown.

Note: Instead of mirroring with wget, saving **whole web page** from browser and replacing `https://ollama-gui.vercel.app` with `/` in the html code also would work I guess.

**Comment by HelgeSverre** [comment]
Not a use case i wanna support at this time, if anyone else want to implement or document this in the readme, open a PR.
