### ISSUE TITLE
Feature Request: allow "editing" the LLM's response

### ISSUE THREAD

**Issue by DeflateAwning** [HelgeSverre/ollama-gui#29]
There are jailbreaks involving editing the LLM's response before it gets passed back to the LLM in the next iteration of the chat chain.

It would be awesome if you could edit the LLM's response, so that the fake/edited version of its reply gets sent back to it in the next chain of the messages.

**Comment by HelgeSverre** [comment]
Not in scope, if anyone wants to take this on, feel free.

**Comment by DeflateAwning** [comment]
Why isn't it in scope? Perhaps you could leave the issue open to centralize discussions (in case anyone else is interested)?

This is a common technique to use for things like Jailbreaks, etc.
