### ISSUE TITLE
It can only visit by localhost:5174, when I visit the webui from another IP, it doesn't work

### ISSUE THREAD

**Issue by gogo7707** [HelgeSverre/ollama-gui#31]
It can only visit by localhost:5174, when I visit the webui from another IP, it doesn't work  , the console.log show interface block by strict-origin-when-cross-origin

**Comment by HelgeSverre** [comment]
Documented here, closing this:
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network
