### ISSUE TITLE
Initial characters from a response are split across answers and are in incorrect order

### ISSUE THREAD

**Issue by svenha** [HelgeSverre/ollama-gui#32]
First, thanks for the helpful project @HelgeSverre !

The initial characters from a response (example here: "Where does the Rhine cross borders?" to mixtral:8x7b, two GPUs correctly used) are split across several answers, and the characters are incorrectly split. It happened for all prompts I tried so far, for the first 10 or 30 characters. 

     Theine crosses

     River borders

     Rh between several countries in Europe. It begins in Switzerland, flowing through or forming a border with Liechtenstein, 
     Austria, Germany, France, and the Netherlands before emptying into the North Sea. This significant river has played a vital role in the history, culture, and economy of many European regions throughout the centuries.

Ideas welcome!

**Comment by HelgeSverre** [comment]
I believe this is fixed now, reopen an issue if it occurs again with the latest version.

**Comment by svenha** [comment]
Is `git pull ; yarn install ; yarn dev` enough to update to the current version? If so, it is not fixed. The Lama icon appears before each partial start (there are three partial starts shown in the original comment).

**Comment by svenha** [comment]
I tested the current version and found out that the issue exists only for some browsers (qutebrowser 2.5), and it does not exist in other browsers (e.g. Brave). So, it is probably not an ollama-gui issue.

**Comment by HelgeSverre** [comment]
@svenha  Is there any errors in the console for those browsers?
