### ISSUE TITLE
Possibility to delete text in chat

### ISSUE THREAD

**Issue by schauppi** [HelgeSverre/ollama-gui#4]
Thx for your great work!

It would be very nice if it were possible to delete the text input from the user or the text output from the model.

**Comment by HelgeSverre** [comment]
Individual chats messages or the entire chat?

I'm working on an [improved version](https://github.com/HelgeSverre/ollama-gui/tree/rewrite) (cleaner code, more features) in the "features/rewrite" branch, where you can delete individual chats and also wipe all chats.

**Comment by schauppi** [comment]
Both. Individual chat messages so you can delete them out of the context window. 
Entire chats just for cleaning up.

**Comment by HelgeSverre** [comment]
The context windows uses the context returned from the ollama API, so deleting a previous message would not technically change the context, however this might be implemented by re-embedding the content upon deletion, i will make a note of this.

Also try out the "rewrite" branch and see if that does what you expect.

**Comment by schauppi** [comment]
In the "rewrite" branch it is not possible for me to delete chats. I do not have an option in the GUI to do achieve this?

**Comment by HelgeSverre** [comment]
Press delete while a chat is highlighted in the sidebar

**Comment by schauppi** [comment]
> Press delete while a chat is highlighted in the sidebar


My Chat looks like this on the rewrite branch:

![Bildschirmfoto 2023-10-16 um 15 15 50](https://github.com/HelgeSverre/ollama-gui/assets/46676413/90cf0de2-2cdf-4516-a981-485dede868de)
