### ISSUE TITLE
Trying to select another model leads to resetting to the first option in the list 

### ISSUE THREAD

**Issue by mihaim** [HelgeSverre/ollama-gui#7]
I have two models installed and when selecting the second from the dropdown menu on new chat, when I start chatting with the model it revers back to the first in the list. 

I'm running locally the latest github pull, as per description.

**Comment by petitwilly** [comment]
the same for me.

**Comment by ug-programmers** [comment]
When will this bug be fixed?

**Comment by HelgeSverre** [comment]
It will be fixed when it will be fixed.

Feel free to make a PR.

**Comment by HelgeSverre** [comment]
Fixed
