### ISSUE TITLE
Models are not loaded 

### ISSUE THREAD

**Issue by dxcore35** [HelgeSverre/ollama-gui#8]
1) I have downloaded several models
2) Server is running

![Screenshot 2023-11-26 at 16 53 13](https://github.com/HelgeSverre/ollama-gui/assets/7279156/afb7a913-dd0f-4969-9599-84a5ca054bfa)

3. No model found 

![Screenshot 2023-11-26 at 16 53 53](https://github.com/HelgeSverre/ollama-gui/assets/7279156/2f2958a5-8be2-4abd-bbe3-c58219c077e0)

**Comment by HelgeSverre** [comment]
Does the latest version work?

**Comment by dxcore35** [comment]
> Does the latest version work?

Whatever you have fixed in new version. After reinstallation the models are loaded! I'm closing the ticket.
